apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-create
          image: d0rka/graph-cluster-backend-phoenix
          command: ['mix']
          args: ['ecto.migrate']
          env:
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGUSER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE_DEVELOPMENT
              value: graph-cluster_development
            - name: PGDATABASE_TEST
              value: graph-cluster_test
            - name: PGDATABASE_PRODUCTION
              value: graph-cluster_production
