apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: d0rka/graph-cluster-backend
          command: ['bundle', 'exec', 'rake']
          args: ['db:migrate']
          env:
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: PGDATABASE_DEVELOPMENT
              value: docker_rails_development
            - name: PGDATABASE_TEST
              value: docker_rails_test
            - name: PGDATABASE_PRODUCTION
              value: docker_rails_production

