apiVersion: batch/v1
kind: Job
metadata:
  name: db-drop
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-drop
          image: d0rka/graph-cluster-backend-phoenix
          command: ['mix']
          args: ['ecto.drop']
          env:
            - name: PGHOST
              value: 127.0.0.1
            - name: PGUSER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE_DEVELOPMENT
              value: graph-cluster_development
            - name: PGDATABASE_TEST
              value: graph-cluster_test
            - name: PGDATABASE_PRODUCTION
              value: graph-cluster_production
        -
          name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          command: ["/cloud_sql_proxy",
                    "-instances=graph-elixir-271706:europe-north1:graph-database=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
