apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-seed
          image: d0rka/graph-cluster-backend-phoenix
          command: ['mix', 'run']
          args: ['priv/repo/seeds.exs']
          env:
            - name: PGHOST
              value: 127.0.0.1
            - name: PGUSER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE_DEVELOPMENT
              value: graph-cluster_development
            - name: PGDATABASE_TEST
              value: graph-cluster_test
            - name: PGDATABASE_PRODUCTION
              value: graph-cluster_production
