apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
    -
      image: d0rka/graph-cluster-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          -
            src: 'src/*'
            dest: .
    -
      image: d0rka/graph-cluster-backend-phoenix
      context: backend_elixir
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          -
            src: 'lib/*'
            dest: .
