apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: d0rka/graph-cluster-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*"
    - image: d0rka/graph-cluster-backend-phoenix
      context: backend_elixir
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*"
    - image: d0rka/graph-cluster-backend-router
      context: backend-router
      docker:
        dockerfile: Dockerfile
