apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-router-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend-router-server
  template:
    metadata:
      labels:
        component: backend-router-server
    spec:
      containers:
        -
          name: backend-router
          image: d0rka/graph-cluster-backend-router
          ports:
            -
              containerPort: 80
          env:
            -
              name: BACKEND_CLUSTER_IP_SERVICE
              value: backend-cluster-ip-service
            -
              name: BACKEND_CLUSTER_IP_SERVICE_PORT
              value: "3000"
            -
              name: FOLDER_SERVICE_BACKEND_CLUSTER_IP_SERVICE
              value: folder-service-backend-cluster-ip-service
            -
              name: FOLDER_SERVICE_BACKEND_CLUSTER_IP_SERVICE_PORT
              value: "3000"
