apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        -
          name: backend
          image: d0rka/graph-cluster-backend-phoenix
          ports:
            -
              containerPort: 3000
          env:
            -
              name: PGHOST
              value: postgres-cluster-ip-service
            -
              name: PGUSER
              value: postgres
            -
              name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            -
              name: PGDATABASE_DEVELOPMENT
              value: graph-cluster_development
            -
              name: PGDATABASE_TEST
              value: graph-cluster_test
            -
              name: PGDATABASE_PRODUCTION
              value: graph-cluster_production
