apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        -
          name: frontend
          image: d0rka/graph-cluster-frontend
          ports:
            -
              containerPort: 3001
          env:
            -
              name: FOLDER_SERVICE_FRONTEND_URL
              value: folder-service-frontend-cluster-ip-service
            -
              name: FOLDER_SERVICE_FRONTEND_PORT
              value: "3001"
